apiVersion: batch/v1
kind: Job
metadata:
  name: geonames-import
spec:
  template:
    metadata:
      name: geonames-import-pod
    spec:
      initContainers:
        - name: create-directories
          image: busybox
          command: ["sh", "-c", "mkdir -p /data/geonames"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
        - name: geonames-download
          image: pelias/geonames
          command: ["npm", "run", "download"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: data-volume
              mountPath: /data
          env:
            - name: PELIAS_CONFIG
              value: "/etc/config/pelias.json"
        - name: wof-download
          image: pelias/whosonfirst
          command: ["npm", "run", "download"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: data-volume
              mountPath: /data
          env:
            - name: PELIAS_CONFIG
              value: "/etc/config/pelias.json"
      containers:
      - name: geonames-import-container
        image: pelias/geonames
        command: ["npm", "start"]
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          - name: data-volume
            mountPath: /data
        env:
          - name: PELIAS_CONFIG
            value: "/etc/config/pelias.json"
        resources:
          limits:
            memory: 3Gi
            cpu: 2
          requests:
            memory: 2Gi
            cpu: 1.5
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: pelias-json-configmap
            items:
              - key: pelias.json
                path: pelias.json
        - name: data-volume
          emptyDir: {}
