apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelias-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pelias-api
    spec:
      containers:
        - name: pelias-api
          image: pelias/api
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          env:
            - name: PELIAS_CONFIG
              value: "/etc/config/pelias.json"
      volumes:
        - name: config-volume
          configMap:
            name: pelias-json-configmap
            items:
              - key: pelias.json
                path: pelias.json
---
apiVersion: v1
kind: Service
metadata:
    name: pelias-api-service
spec:
    selector:
        app: pelias-api
    ports:
        - protocol: TCP
          port: 3100
