# override this to use external elasticsearch
elasticsearch:
  host: "elasticsearch-service"
  port: 9200
  protocol: "http"

## API settings
api:
  replicas: 1
  canaryReplicas: 0
  dockerTag: "latest"
  canaryDockerTag: null # set this value to enable the canary deployment
  indexName: "pelias"
  attributionURL: "http://api.yourpelias.com/attribution"
  # Whether the API service should be externally accessible
  # Set this to true if you want to, for example on AWS, set up an ELB for the API
  externalService: false
  # whether the external service  should be internet facing or private (default private)
  privateLoadBalancer: true
  autocomplete:
    exclude_address_length: 0
  requests:
    memory: 0.25Gi
    cpu: 0.1
  minReadySeconds: 10

placeholder:
  enabled: true
  replicas: 1
  host: "http://pelias-placeholder-service:3000/"
  dockerTag: "latest"
  storeURL: "https://s3.amazonaws.com/pelias-data.nextzen.org/placeholder/store.sqlite3.gz"
  retries: 1 # number of time the API will retry requests to placeholder
  timeout: 5000 # time in ms the API will wait for placeholder responses

libpostal:
  enabled: true
  replicas: 1
  host: "http://pelias-libpostal-service:4400/"
  dockerTag: "latest"
  retries: 1 # number of time the API will retry requests to libpostal
  timeout: 5000 # time in ms the API will wait for libpostal responses

# Whether the dashboard should be set up
dashboard:
  enabled: true
  domain: null # set this to enable an ingress

interpolation:
  enabled: false
  host: "http://pelias-interpolation-service:3000/"
  pvc: {}
#    create: true
#    name: interpolation-pvc
#    storageClass: aws-efs
#    accessModes: ReadWriteMany
#    storage: 10Gi
#    annotations: {}

pip:
  enabled: true
  host: "http://pelias-pip-service:3102/"
  pvc: {}
#    create: true
#    name: pip-pvc
#    storageClass: aws-efs
#    accessModes: ReadWriteMany
#    storage: 10Gi
#    annotations: {}


# Deprecated fields
# pipEnabled: true
# pipHost: "http://pelias-pip-service:3102/"

# interpolationEnabled: false
# interpolationHost: "http://pelias-interpolation-service:3000/"
